services:
  db:
    image: postgres:14-alpine3.20
    environment:
      POSTGRES_USER: midas  
      POSTGRES_PASSWORD: midas2k25  
      POSTGRES_DB: midasdb
    ports:
      - "5432:5432"
    volumes:
      - midas:/var/lib/postgresql/data

volumes:
  midas: